#!/usr/bin/env bash
# Cut a hello_build release and publish it to the static registry
# (github.com/altdansalt/bazel-registry — ADR 0023).
#
#   ./release.sh <version>
#
# Preconditions: clean tree pushed to origin, MODULE.bazel module() version
# already bumped to <version>, gh auth'ed, registry checkout at
# $REGISTRY_DIR (default ~/bazel-registry).
#
# Publishes: git tag v<version>; a `git archive` tarball as the GitHub
# release asset (stable artifact — never the autogenerated /archive/ URL);
# the registry entry (MODULE.bazel copy, source.json with sha256 integrity,
# metadata.json version list).
#
# The release tests its claim (ADR 0010): before the registry entry is
# pushed, a scratch workspace must fetch @hello_build at this version
# through a file:// view of the registry — exercising version match,
# asset URL, integrity, and strip_prefix exactly as a consumer would
# (`bazel query`, not `bazel mod`: mod eagerly evaluates every module
# extension, which a bare consumer never does). On failure the tag and
# GitHub release are rolled back; nothing half-released remains.
set -euo pipefail

version=${1:?usage: release.sh <version>}
repo_root=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
cd "$repo_root"

[ -z "$(git status --porcelain)" ] || { echo "working tree not clean" >&2; exit 1; }
# Check the module() block specifically — MODULE.bazel is full of crate
# version lines an unanchored grep can match (the v0.2.1 incident).
sed -n '/^module(/,/^)/p' MODULE.bazel | grep -qF "version = \"$version\"" || {
  echo "MODULE.bazel module() version is not $version — bump it first" >&2; exit 1; }
[ "$(git rev-parse HEAD)" = "$(git ls-remote origin HEAD | cut -f1)" ] || {
  echo "HEAD not pushed to origin" >&2; exit 1; }

reg=${REGISTRY_DIR:-$HOME/bazel-registry}
mod=$reg/modules/hello_build
[ -z "$(git -C "$reg" status --porcelain)" ] || {
  echo "registry checkout $reg not clean" >&2; exit 1; }

tag=v$version
git tag "$tag"
git push -q origin "$tag"
archive=$(mktemp -d)/hello_build-$version.tar.gz
git archive --format=tar.gz --prefix="hello_build-$version/" -o "$archive" "$tag"
gh release create "$tag" "$archive" --title "hello_build $version" \
  --notes "Static-registry release. Consume via bazel_dep + the registries in https://github.com/altdansalt/bazel-registry."
integrity="sha256-$(openssl dgst -sha256 -binary "$archive" | base64)"

mkdir -p "$mod/$version"
git show "$tag:MODULE.bazel" > "$mod/$version/MODULE.bazel"
cat > "$mod/$version/source.json" <<EOF
{
  "integrity": "$integrity",
  "strip_prefix": "hello_build-$version",
  "url": "https://github.com/altdansalt/hello-build/releases/download/$tag/hello_build-$version.tar.gz"
}
EOF
tmp=$(mktemp)
jq --arg v "$version" '.versions = ((.versions + [$v]) | unique)' \
  "$mod/metadata.json" > "$tmp" && mv "$tmp" "$mod/metadata.json"

check=$(mktemp -d)
cp .bazelversion "$check/"
printf 'common --registry=file://%s\ncommon --registry=https://bcr.bazel.build\n' \
  "$reg" > "$check/.bazelrc"
cat > "$check/MODULE.bazel" <<EOF
module(name = "release_check")
bazel_dep(name = "hello_build", version = "$version")
EOF
touch "$check/BUILD.bazel"
if ! (cd "$check" && bazel query '@hello_build//tools:all' >/dev/null 2>"$check/err"); then
  echo "release self-check FAILED: $version does not fetch as a consumer would" >&2
  tail -20 "$check/err" >&2
  git -C "$reg" checkout -q -- . && git -C "$reg" clean -qfd
  gh release delete "$tag" --yes
  git push -q origin ":refs/tags/$tag"
  git tag -d "$tag"
  echo "rolled back tag, GitHub release, and registry entry" >&2
  exit 1
fi

git -C "$reg" add -A
git -C "$reg" commit -q -m "hello_build $version"
git -C "$reg" push -q
echo "released hello_build $version ($tag, integrity $integrity, consumer-checked)"
