#!/usr/bin/env bash
# Cut a hello_build release and publish it to the static registry
# (github.com/altdansalt/bazel-registry — ADR 0023).
#
#   ./release.sh <version>
#
# Preconditions: clean tree pushed to origin, MODULE.bazel module() version
# already bumped to <version>, gh auth'ed, registry checkout at
# $REGISTRY_DIR (default ~/bazel-registry).
#
# Publishes: git tag v<version>; a `git archive` tarball as the GitHub
# release asset (stable artifact — never the autogenerated /archive/ URL);
# the registry entry (MODULE.bazel copy, source.json with sha256 integrity,
# metadata.json version list).
set -euo pipefail

version=${1:?usage: release.sh <version>}
repo_root=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
cd "$repo_root"

[ -z "$(git status --porcelain)" ] || { echo "working tree not clean" >&2; exit 1; }
# Check the module() block specifically — MODULE.bazel is full of crate
# version lines an unanchored grep can match (the v0.2.1 incident).
sed -n '/^module(/,/^)/p' MODULE.bazel | grep -qF "version = \"$version\"" || {
  echo "MODULE.bazel module() version is not $version — bump it first" >&2; exit 1; }
[ "$(git rev-parse HEAD)" = "$(git ls-remote origin HEAD | cut -f1)" ] || {
  echo "HEAD not pushed to origin" >&2; exit 1; }

tag=v$version
git tag "$tag"
git push -q origin "$tag"

archive=$(mktemp -d)/hello_build-$version.tar.gz
git archive --format=tar.gz --prefix="hello_build-$version/" -o "$archive" "$tag"
gh release create "$tag" "$archive" --title "hello_build $version" \
  --notes "Static-registry release. Consume via bazel_dep + the registries in https://github.com/altdansalt/bazel-registry."
integrity="sha256-$(openssl dgst -sha256 -binary "$archive" | base64)"

reg=${REGISTRY_DIR:-$HOME/bazel-registry}
mod=$reg/modules/hello_build
mkdir -p "$mod/$version"
git show "$tag:MODULE.bazel" > "$mod/$version/MODULE.bazel"
cat > "$mod/$version/source.json" <<EOF
{
  "integrity": "$integrity",
  "strip_prefix": "hello_build-$version",
  "url": "https://github.com/altdansalt/hello-build/releases/download/$tag/hello_build-$version.tar.gz"
}
EOF
tmp=$(mktemp)
jq --arg v "$version" '.versions = ((.versions + [$v]) | unique)' \
  "$mod/metadata.json" > "$tmp" && mv "$tmp" "$mod/metadata.json"

# The release tests its claim (ADR 0010) before the registry push: a scratch
# workspace must resolve this exact version from the local registry checkout.
check=$(mktemp -d)
cp .bazelversion "$check/"
cat > "$check/MODULE.bazel" <<EOF
module(name = "release_check")
bazel_dep(name = "hello_build", version = "$version")
EOF
touch "$check/BUILD.bazel"
(cd "$check" && bazel mod deps --registry="file://$reg" \
  --registry=https://bcr.bazel.build >/dev/null 2>"$check/err") || {
  echo "release self-check FAILED: $version does not resolve from the registry" >&2
  cat "$check/err" >&2
  git -C "$reg" checkout -q -- . && git -C "$reg" clean -qfd
  exit 1
}

git -C "$reg" add -A
git -C "$reg" commit -q -m "hello_build $version"
git -C "$reg" push -q
echo "released hello_build $version ($tag, integrity $integrity, resolution-checked)"
