load("@hello_build//tools:autotools.bzl", "configure_static_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "tree",
    srcs = glob(["**"]),
)

exports_files(["configure"])

configure_static_library(
    name = "pcre",
    srcs = [":tree"],
    configure = "configure",
    configure_args = [
        "--disable-cpp",
        "--disable-shared",
        "--enable-static",
        "--enable-unicode-properties",
        "--enable-utf",
    ],
    hdrs = [
        "include/pcre.h",
        "include/pcreposix.h",
    ],
    static_library = "lib/libpcre.a",
)
