"""Source facts for the_silver_searcher 2.2.0.

Generated by reading upstream Makefile.am `ag_SOURCES`; compile/link flags are
from configure.ac plus a verbose scratch build with pinned PCRE, zlib, and xz.
"""

AG_SRCS = [
    "src/decompress.c",
    "src/ignore.c",
    "src/lang.c",
    "src/log.c",
    "src/main.c",
    "src/options.c",
    "src/print.c",
    "src/print_w32.c",
    "src/scandir.c",
    "src/search.c",
    "src/util.c",
    "src/zfile.c",
]

AG_HDRS = [
    "src/decompress.h",
    "src/ignore.h",
    "src/lang.h",
    "src/log.h",
    "src/options.h",
    "src/print.h",
    "src/scandir.h",
    "src/search.h",
    "src/uthash.h",
    "src/util.h",
]

AG_COPTS = [
    "-O2",
    "-fcommon",
    "-Wall",
    "-Wextra",
    "-Wformat=2",
    "-Wno-format-nonliteral",
    "-Wshadow",
    "-Wpointer-arith",
    "-Wcast-qual",
    "-Wmissing-prototypes",
    "-Wno-missing-braces",
    "-std=gnu89",
    "-D_GNU_SOURCE",
]
