load("@hello_build//tools:autotools.bzl", "configure_static_library")

package(default_visibility = ["//visibility:public"])

LZMA_HEADERS = [
    "include/lzma.h",
    "include/lzma/base.h",
    "include/lzma/bcj.h",
    "include/lzma/block.h",
    "include/lzma/check.h",
    "include/lzma/container.h",
    "include/lzma/delta.h",
    "include/lzma/filter.h",
    "include/lzma/hardware.h",
    "include/lzma/index.h",
    "include/lzma/index_hash.h",
    "include/lzma/lzma12.h",
    "include/lzma/stream_flags.h",
    "include/lzma/version.h",
    "include/lzma/vli.h",
]

filegroup(
    name = "tree",
    srcs = glob(["**"]),
)

exports_files(["configure"])

configure_static_library(
    name = "lzma",
    srcs = [":tree"],
    configure = "configure",
    configure_args = [
        "--disable-doc",
        "--disable-lzmadec",
        "--disable-lzmainfo",
        "--disable-nls",
        "--disable-scripts",
        "--disable-shared",
        "--disable-xz",
        "--disable-xzdec",
        "--enable-static",
    ],
    hdrs = LZMA_HEADERS,
    static_library = "lib/liblzma.a",
)
