load("@hello_build//tools:autotools.bzl", "configure_static_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "tree",
    srcs = glob(["**"]),
)

exports_files(["configure"])

configure_static_library(
    name = "zlib",
    srcs = [":tree"],
    configure = "configure",
    configure_args = ["--static"],
    hdrs = [
        "include/zconf.h",
        "include/zlib.h",
    ],
    static_library = "lib/libz.a",
)
